#!/usr/bin/env bash
# Find the PID of the running script
script_pid=$(pgrep -f "4-to_infinity_and_beyond.sh")

# Check if the script is running
if [ -n "$script_pid" ]; then
    # Stop the script by sending a SIGTERM signal
    kill $script_pid
    echo "Script stopped."
else
    echo "Script is not running."
fi
