#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times.

# Initialize a counter
counter=0

# Using an until loop to display "Best School" 10 times
until [ $counter -ge 10 ]; do
    echo "Best School"
    # Increment the counter
    ((counter++))
done
