#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration,
# displays Best School and then Hi on a new line.

# Initialize a counter
counter=0

# Using a while loop to display "Best School" 10 times
while [ $counter -lt 10 ]; do
    if [ $counter -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    # Increment the counter
    ((counter++))
done


# Initialize a counter
counter=0

# Using a while loop to display "Best School" 10 times
while [ $counter -lt 10 ]; do
    if [ $counter -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    # Increment the counter
    ((counter++))
done
